website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .forms import RegisterForm, LoginForm
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import re

auth = Blueprint('auth', __name__)

@auth.route('/', methods=['GET', 'POST'])
def login():
    logout_user()
    form = LoginForm()
    
    if request.method == 'POST':
        username = form.username.data
        password= form.password.data
        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password_hash, password):
                flash('Logged In Successfully!', category='success')
                login_user(user, remember=True)

                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Credentials', category='error')
        else:
            flash('User Does Not Exist', category='error')

    return render_template("login.html", form=form, user= current_user)



@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))



@auth.route('/register',methods=['GET', 'POST'])
def register():
    logout_user()
    form = RegisterForm()
    regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
    if request.method == 'POST':
        email = form.email.data
        username = form.username.data
        password= form.password.data
        password2= form.password.data
        user = User.query.filter_by(username=username).first()
        email_inDB = User.query.filter_by(email=email).first()
        if user or email_inDB:
            flash('Account already exists', category='error')
        elif not re.search(regex,email):
            flash('Invalid Email', category='error')
        elif len(username) <2:
            flash('Username too short', category='error')
        elif password != password2:
            flash('Passwords do not match', category='error')
        else:
            #add user to database
            new_user = User(email=email, username=username, password_hash= generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created', category='success')
            return redirect(url_for('views.home'))
    return render_template("register.html", form=form, user=current_user)
    

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import  login_required, current_user
from . import db
from website.auth import login
from .forms import PostForm, CommentForm
from .models import Post, Comments
import cloudinary
import cloudinary.uploader
import timeago, datetime

views = Blueprint('views', __name__)
ALLOWED_EXTENSIONS = ["png", "jpg", "jpeg", "gif"]
def time_ago(date):
        now=datetime.datetime.utcnow() + datetime.timedelta(seconds = 60 * 3.4)
        
        return timeago.format(date, now)

        
@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    
    form = PostForm()
    all_posts = Post.query.all()
    
    if request.method == "POST":
        
        user_id = current_user.id 
        title = form.title.data
        description= form.description.data
        img_name_main = form.img_file.data

        if img_name_main.filename.split(".")[-1].lower() in ALLOWED_EXTENSIONS:    
            upload_result = cloudinary.uploader.upload(img_name_main,use_filename = True, unique_filename = False)
            
            new_post = Post(title=title, description=description, img_name=upload_result.get("secure_url"), user_id=user_id)
        
            db.session.add(new_post)
            db.session.commit()

            flash('Post created', category='success')
            return redirect(url_for('views.home'))
        else:
            flash('Please Enter a Valid Image Type', category='error')
            

    return render_template("home.html", user=current_user, time_ago= time_ago,form=form, posts=all_posts, postable=True)



    


@views.route('/delete_post/<int:user_id>/<int:post_id>')
@login_required
def delete_post(user_id, post_id):

   
   if user_id == current_user.id:
        delete_post = Post.query.get(post_id)
        #using db.session delete the item
        db.session.delete(delete_post)
        #commit the deletion
        db.session.commit()
        return redirect(url_for('views.home'))
   return redirect(url_for('views.home'))

@views.route('/update_post/<int:user_id>/<int:post_id>', methods=["GET", "POST"])
@login_required
def update_post(user_id, post_id):
    form = PostForm()
    
    all_posts = Post.query.all()
    if user_id == current_user.id:
        post_to_update= Post.query.get(post_id)
        if request.method=="POST":
            post_to_update.title= form.title.data
            post_to_update.description = form.description.data
            try:
                db.session.commit()
                flash('Post Updated', category='success')
                return redirect(url_for('views.home'))
            except:
                flash('Post Could Not Be Updated', category='error')



    return render_template("home.html", user=current_user, time_ago=time_ago, form=form, posts=all_posts, post_update=post_to_update, postable=False)


        


@views.route('/comments/<int:postId>', methods=["GET", "POST"])
@login_required
def comments(postId):
    form = CommentForm()
    post = Post.query.get(postId)
    comments= Comments.query.filter_by(post_id = post.id).all()
    if request.method=="POST":
        comment = form.comment.data

        
        new_comment = Comments(comment=comment, post_id= postId, user_commenter_id = current_user.id )
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment Posted', category='success')
        return redirect(url_for('views.comments', postId=postId))
    




    return render_template("view_comments.html", user=current_user, post=post, form=form,comments=comments)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='../static/static.css') }}" />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
  
    <nav class="navbar navbar-expand-lg navbar-dark gradient-custom-2">
      <div class="container-fluid">
        <a class="navbar-brand mb-0 ml-3 h1">Post Pic</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
            {%if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/logout">Logout</a>
            </li>
            
            {%else%}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/register">Register</a>
            </li>
            {%endif%}
          </ul>
          {%if user.is_authenticated%}
          <a class="navbar-brand mb-0 h3" href="/home">Welcome {{user.username}}</a>
            
          {%endif%}
        </div>
      </div>
    </nav>
   
    {%with messages = get_flashed_messages(with_categories=true)%}
      {%if messages%}
      
        {%for category, message in messages%}
          {%if category == 'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>

          </div>
          {%else%}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>

          </div>
          {%endif%}
        {%endfor%}
      {%endif%}
    {%endwith%}
    
    {%block content%}
    {%endblock%}
  





















    


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %}
{%block title%}Home{%endblock%}


{%block content%}
    
    <div class="container mt-4" id="content">
        
        <div class="row row-cols-4">
            {%if postable%}
            <form method="POST" enctype = "multipart/form-data" >
                <div class="col">
                    <h3>New Post</h3>
                    <div class="mb-3">
                        {{form.title.label}}
                        {{form.title(placeholder_="Enter Title", class_='form-control')}}
                    </div>
                    <div class="mb-3">
                        {{form.description.label}}
                        {{form.description(placeholder_="Enter Description", class_='form-control', col="30", row="30")}}
                    </div>
                    <div class="mb-3">
                        {{form.img_file.label}}
                        {{form.img_file(class_='form-control')}}
                    </div>
                    <br/>
                    <button class="empty">{{form.submit(class_="btn gradient-custom-2 btn-primary")}}</button>
                    
                </div>
            </form>
            {%else%}
            <form method="POST" enctype = "multipart/form-data" >
                <div class="col">
                    <h3>Update Post</h3>
                    <div class="mb-3">
                        {{form.title.label}}
                        {{form.title(placeholder_="Enter Title", class_='form-control', value=post_update.title)}}
                    </div>
                    <div class="mb-3">
                        {{form.description.label}}
                        {{form.description(placeholder_="Enter Description", class_='form-control', value=post_update.id,  col="30", row="30")}}
                    </div>
                    <br/>
                    <p>{{form.submit(class_="btn gradient-custom-2 btn-primary")}}</p>
                </div>
            </form>
            {%endif%}
            <div class="col-9">
                
                <div class="d-flex align-content-start flex-wrap">
                    {%for post in posts%}
                        <div class="card mb-4 mr-4 border border-primary p-2" style="width: 18rem;">
                            <img src="{{post.img_name}}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">{{post.title}}</h5>
                              <p class="card-text">{{post.description}}</p>
                              
                              <p class="card-text text-info">Posted By: {{post.user.username}}</p>
                              <br/>
                            </div>
                            <div class="text-center">
                            
                                <a href="{{url_for('views.comments', postId=post.id)}}" class="btn gradient-custom-2 btn-primary">Comments</a>
                                {%if user.id == post.user.id%}
                                    <a href="{{url_for('views.update_post', user_id= user.id, post_id= post.id)}}" class="btn btn-warning "><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                    </svg></a>  
                                    <a href="{{url_for('views.delete_post', user_id= user.id, post_id= post.id)}}" class="btn btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                                    </svg></a>
                                    
                                    
                                {%endif%}
                            </div>        
                                
                            
                        </div>
                    {%endfor%}
                      
                </div>
            </div>
        </div>
    </div>

{%endblock%}

website/templates/login.html
{% extends "base.html" %}
{%block title%}Login{%endblock%}


{%block content%}

<div class="container-fluid h-custom mt-5">
   <div class="row d-flex justify-content-center align-items-center h-100">
     
     <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
       <form method="POST">            
         <h3 align="center">Login</h3>
         <div class="form-outline mb-4">
            {{form.username.label}}
            {{form.username(placeholder_="Enter Username", class_='form-control')}}
         </div>
        
         <div class="form-outline mb-3">
            {{form.password.label}}
            {{form.password(placeholder_="Enter Password", class_='form-control')}}
         </div>
         <div class="d-flex justify-content-between align-items-center">
           <!-- Checkbox -->
           <div class="form-check mb-0">
             <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
             <label class="form-check-label" for="form2Example3">
               Remember me
             </label>
           </div>
          
         </div>
         <div class="text-center text-lg-start mt-4 pt-2">
            <p>{{form.submit(class_="btn btn-primary gradient-custom-2 btn-lg")}}</p>
           <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{{url_for('auth.register')}}"
               class="link-danger">Register</a></p>
         </div>
       </form>
       
     </div>
     <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="../static/tttitle.PNG"
          class="img-fluid rounded" alt="Sample image">
      </div>
   </div>
 </div>
      
        
{%endblock%}

website/templates/register.html
{% extends "base.html" %}
{%block title%}Register{%endblock%}


{%block content%}
    <div class="container mt-4">
    <form method="POST">
        <h3 align="center">Register</h3>
        <div class="form-group">
            {{form.email.label}}
            {{form.email(placeholder_="Enter Email", class_='form-control')}}

        </div>
        <div class="form-group">
            {{form.username.label}}
            {{form.username(placeholder_="Enter Username", class_='form-control')}}
        </div>
        <div class="form-group">
            {{form.password.label}}
            {{form.password(placeholder_="Enter Password", class_='form-control')}}
        </div>
        <div class="form-group">
            {{form.password2.label}}
            {{form.password(placeholder_="ReType Password", class_="form-control")}}
        </div>
        <br/>
        <p>{{form.submit(class_="btn gradient-custom-2 btn-lg btn-primary")}}</p>
        <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account? <a href="{{url_for('auth.login')}}"
            class="link-danger">Login</a></p>
        
    </form>
    </div>
{%endblock%}

website/templates/view_comments.html
{% extends "base.html" %}
{%block title%}Comments{%endblock%}


{%block content%}
    <a href="{{url_for('views.home')}}" class="mt-5 ml-5">
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="red" class="bi bi-backspace-fill" viewBox="0 -10 32 32">
      <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"/>
        </svg>
    </a>
    <div class="container">
        
        <div class="container">
          <h1 class="mt-3 mb-3">{{post.title}}</h1> 
          <h4 class="mb-3"><em>{{post.description}}</em></h4>  
        </div>
        <div class="text-center">
            <img src="{{post.img_name}}" class="img-fluid" alt="...">
        </div>
        <div class="container-sm w-50 p-5">
            <ul class="list-group">
            {%if comments|length !=0 %}
            {%for comment in comments%}
                
                    <li class="list-group-item"><strong>{{comment.user_commenter.username}}:</strong>  {{comment.comment}}</li>
                    
             
            {%endfor%}
            {%else%}
            <li class="list-group-item"><strong>Be The First to Comment!</strong></li>
            {%endif%}
        
            </ul>
            <div class="mt-5">
                <form method="POST">

                    <div class="input-group">
                        {{form.comment(placeholder_="Enter Comment", class_='form-control')}}
                        {{form.submit(class_="btn btn-outline-primary")}}
                        
                    </div>
                    
                
                </form>
            </div>
        </div>    
    </div>
{%endblock%}